name: 'Ansible playbook test workflow (custom callback)'
on: [push]
defaults:
  run:
    shell: bash
env:
  ANSIBLE_FORCE_COLOR: True
  ANSIBLE_STDOUT_CALLBACK: custom

jobs:
  run-minikube-test-cluster:
    name: 'Run a minikube test cluster'
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Start minikube
        run: ansible-playbook start-minikube.yml

      - name: Display nodes
        run: oc get nodes
